# Generated by Django 4.1.3 on 2022-11-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Koylak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavsumi', models.CharField(max_length=20)),
                ('uzunligi', models.CharField(max_length=20)),
                ('olchami', models.IntegerField(default=1)),
            ],
        ),
    ]
