# Generated by Django 4.1.3 on 2022-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiyim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangi', models.CharField(max_length=20)),
                ('olchami', models.IntegerField(default=1)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Kofta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matosi', models.CharField(max_length=20)),
                ('olchami', models.IntegerField(default=1)),
                ('soni', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Palto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matosi', models.CharField(max_length=20)),
                ('uzunligi', models.TextField()),
                ('olchami', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rubashka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangi', models.TextField()),
                ('olchami', models.IntegerField(default=1)),
                ('narxi', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tufli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matosi', models.TextField()),
                ('turi', models.CharField(max_length=20)),
                ('olchamini', models.IntegerField(default=1)),
            ],
        ),
    ]
